spring:
  profiles:
    active:
      - dev

---

spring:
  profiles:
    active: dev
  application:
    name: atguigu-dev

---
spring:
  profiles:
    active: dev
  application:
    name: atguigu-test

##